### ISSUE TITLE
The class RandStream has no Constant property or Static method named 'setDefaultStream'.

### ISSUE THREAD

**Issue by kareth-leon** [rjgsousa/RSROSVM#1]
Hi, thanks a lot for sharing your code. I tried to run it but I have this issue:
`The class RandStream has no Constant property or Static method named
'setDefaultStream'.`
I have tried different things and it doesn't work. I would like to run the SVM classifier with the reject option.
Thanks in advance.

**Comment by rjgsousa** [comment]
Hi @kareth-leon 

Thanks for your query. This code was built on top of an old version of the Matlab. Since you have close the issue, can I assume that the bug that you have mentioned is already fixed?

Thank you for your time,

Regards,
Ricardo G. Sousa
